{"name": "Проверка создания курьера с повторяющимся логином ", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин уже используется. Попробуйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_courier.TestCourier object at 0x000001E682F4CC10>\nnew_courier = ['desfnsnxgk', 'wtxgkibveb', 'hzzrflbprf']\nprepare_user = <function prepare_user.<locals>._prepare_user at 0x000001E682F93240>\n\n    @allure.title('Проверка создания курьера с повторяющимся логином ')\n    def test_create_two_courier(self, new_courier, prepare_user):\n        with allure.step('Генерация данных курьера'):\n            login, password, first_name = new_courier\n            payload = {\n                \"login\": login,\n                \"password\": password,\n                \"firstName\": first_name\n            }\n        with allure.step('Отправка двух POST запросов, используя сгенерированные данные'):\n            response = requests.post(f'{url}courier', data=payload)\n            response2 = requests.post(f'{url}courier', data=payload)\n        r = response2.json()\n        prepare_user(payload)\n    \n        with allure.step(\"Проверка сообщения об ошибке\"):\n>           assert r['message'] == \"Этот логин уже используется\"\nE           AssertionError: assert 'Этот логин уже используется. Попробуйте другой.' == 'Этот логин уже используется'\nE             - Этот логин уже используется\nE             + Этот логин уже используется. Попробуйте другой.\n\ntest_courier.py:67: AssertionError"}, "steps": [{"name": "Генерация данных курьера", "status": "passed", "start": 1699092369617, "stop": 1699092369617}, {"name": "Отправка двух POST запросов, используя сгенерированные данные", "status": "passed", "start": 1699092369617, "stop": 1699092370158}, {"name": "Проверка сообщения об ошибке", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин уже используется. Попробуйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.\n", "trace": "  File \"C:\\Users\\polin\\PycharmProjects\\sprint_7\\tests\\test_courier.py\", line 67, in test_create_two_courier\n    assert r['message'] == \"Этот логин уже используется\"\n"}, "start": 1699092370377, "stop": 1699092370378}], "start": 1699092369616, "stop": 1699092370380, "uuid": "3439bb1d-a6b9-4f9b-a0cc-1743c02aa2ee", "historyId": "93b57df273af157250aa4571dbb98f93", "testCaseId": "93b57df273af157250aa4571dbb98f93", "fullName": "test_courier.TestCourier#test_create_two_courier", "labels": [{"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourier"}, {"name": "host", "value": "LAPTOP-6O4U7BT3"}, {"name": "thread", "value": "18440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier"}]}